### ISSUE TITLE
Существует ли пример из документации в онлайн сервисах?

### ISSUE THREAD

**Issue by rtxrulez** [rajdee/redux-in-russian#110]
Было бы удобно сразу попробовать приложение из документации на онлайн сервисах которые работают с react. На таких как https://codesandbox.io например.

**Comment by rajdee** [comment]
@rtxrulez Готовых песочниц не встречал, но практически все современные песочницы позволяют подключать сторонние библиотеки, поэтому написать пример не совставляет труда или поискать готовые примеры
