### ISSUE TITLE
Ссылки на уроки на Русском

### ISSUE THREAD

**Issue by kulakowka** [rajdee/redux-in-russian#27]
Хорошая статья на Хабре: https://habrahabr.ru/post/269831/ 

Мне удалось разобраться с её помощью. 

Возможно стоит добавить ссылки на русскоязычные статьи в README.md ??? 
Если поскрести по хабру, тостеру и другим ресурсам, наверняка найдется масса полезных материалов.

Что скажите @rajdee ?

**Comment by jt3k** [comment]
Здесь же всего-лишь репозиторий переведёнки с [этой репы](https://github.com/rackt/redux).
@kulakowka  для ваших целей лучше всего будет создать новый репозиторий где будут ссылки на разный материал по реакту/редуксу, и попросить @rajdee поместить ссылку на этот новый репозиторий.
