### ISSUE TITLE
Выгрузка в GitBook

### ISSUE THREAD

**Issue by keslo** [rajdee/redux-in-russian#42]
Можно ли выгрузить материал в GitBook? Хорошо иметь возможность получить материал в виде ePub/pdf.

**Comment by rajdee** [comment]
Перевод доступен в GitBook уже около 2 недель, [ссылка](https://rajdee.gitbooks.io/redux-in-russian/content/) указана в самом начале репозитория

**Comment by keslo** [comment]
Отлично! Спасибо.
